# Generated by Django 5.2.16 on 2026-07-31 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis Organisasi',
                'verbose_name_plural': 'Jenis Organisasi',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Organisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_organisasi', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('nomor_sk', models.CharField(blank=True, max_length=100)),
                ('tanggal_sk', models.DateField(blank=True, null=True)),
                ('tanggal_berdiri', models.DateField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to='organisasi/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('status_verifikasi', models.BooleanField(default=False)),
                ('desa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.desa')),
                ('jenis_organisasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisasi.jenisorganisasi')),
                ('ketua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnggotaOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nik', models.CharField(max_length=16)),
                ('jabatan', models.CharField(max_length=100)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('organisasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisasi.organisasi')),
            ],
        ),
    ]
