# Generated by Django 5.2.16 on 2026-08-01 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisasi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersyaratanOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('wajib', models.BooleanField(default=True)),
                ('jenis_organisasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisasi.jenisorganisasi')),
            ],
        ),
        migrations.CreateModel(
            name='DokumenOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='organisasi/')),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], default='MENUNGGU', max_length=20)),
                ('catatan_verifikasi', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('organisasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='organisasi.organisasi')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('persyaratan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisasi.persyaratanorganisasi')),
            ],
        ),
    ]
