# Generated by Django 4.2.30 on 2026-08-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisasi', '0002_persyaratanorganisasi_dokumenorganisasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisasi',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisasi',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
