# Generated by Django 5.2.17 on 2026-08-26 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisasi', '0003_alter_organisasi_latitude_alter_organisasi_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dokumenorganisasi',
            constraint=models.UniqueConstraint(fields=('organisasi', 'persyaratan'), name='unique_organisasi_persyaratan'),
        ),
    ]
