# Generated by Django 5.2.16 on 2026-08-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifikasi',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='jenis',
            field=models.CharField(choices=[('PENGADUAN', 'Pengaduan'), ('ORGANISASI', 'Organisasi'), ('BERITA', 'Berita'), ('SISTEM', 'Sistem')], default='SISTEM', max_length=20),
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
