# Generated by Django 5.2.16 on 2026-08-01 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informasi', '0004_materiberitalike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriBeritaActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktivitas', models.CharField(choices=[('LIKE', 'Like'), ('VIEW', 'View')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='informasi.materiberita')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MateriBeritaLike',
        ),
        migrations.AddIndex(
            model_name='materiberitaactivity',
            index=models.Index(fields=['materi', 'aktivitas'], name='informasi_m_materi__497cff_idx'),
        ),
    ]
