# Generated by Django 5.2.16 on 2026-08-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informasi', '0005_materiberitaactivity_delete_materiberitalike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiberita',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, upload_to='materi/pdf/'),
        ),
        migrations.AlterField(
            model_name='materiberita',
            name='kategori',
            field=models.CharField(choices=[('BERITA', 'Berita'), ('MATERI', 'Materi')], max_length=20),
        ),
    ]
