# Generated by Django 4.2.30 on 2026-08-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informasi', '0006_materiberita_file_pdf_alter_materiberita_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='status_kirim',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
