# Generated by Django 5.2.16 on 2026-08-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_desa_latitude_alter_desa_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desa',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desa',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
