# Generated by Django 4.2.30 on 2026-07-30 20:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('KABAN', 'Kaban'), ('SEKBAN', 'Sekban'), ('KABID', 'Kabid'), ('ANGGOTA', 'Anggota'), ('MASYARAKAT', 'Masyarakat')], default='MASYARAKAT', max_length=20)),
                ('nik', models.CharField(blank=True, max_length=16, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JenisKasus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JenisOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis Organisasi',
                'verbose_name_plural': 'Jenis Organisasi',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_tiket', models.CharField(max_length=50, unique=True)),
                ('nama_pelapor', models.CharField(blank=True, max_length=255)),
                ('hp_pelapor', models.CharField(blank=True, max_length=20)),
                ('email_pelapor', models.EmailField(blank=True, max_length=254)),
                ('alamat_pelapor', models.TextField(blank=True)),
                ('lokasi_kejadian', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('waktu_kejadian', models.DateTimeField()),
                ('uraian', models.TextField()),
                ('pihak_terlibat', models.TextField(blank=True)),
                ('dampak', models.TextField(blank=True)),
                ('prioritas', models.CharField(default='SEDANG', max_length=20)),
                ('anonim', models.BooleanField(default=False)),
                ('source', models.CharField(default='WEB', max_length=20)),
                ('status', models.CharField(choices=[('BARU', 'BARU'), ('VERIFIKASI', 'VERIFIKASI'), ('DISPOSISI', 'DISPOSISI'), ('PROSES', 'PROSES'), ('MONITORING', 'MONITORING'), ('SELESAI', 'SELESAI'), ('DITUTUP', 'DITUTUP'), ('DITOLAK', 'DITOLAK')], default='BARU', max_length=25)),
                ('verifikasi_admin', models.BooleanField(default=False)),
                ('kesimpulan', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.desa')),
                ('jenis_kasus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.jeniskasus')),
                ('pelapor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifikasiPengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peran', models.CharField(choices=[('PJ', 'Penanggung Jawab'), ('TIM', 'Tim')], max_length=10)),
                ('status_verifikasi', models.BooleanField(default=False)),
                ('catatan', models.TextField(blank=True)),
                ('tanggal_verifikasi', models.DateTimeField(blank=True, null=True)),
                ('pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pengaduan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('is_verified', models.BooleanField(default=False)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bidang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bidang')),
                ('desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.desa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PengaduanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('status_lama', models.CharField(max_length=25)),
                ('status_baru', models.CharField(max_length=25)),
                ('dokumentasi', models.FileField(blank=True, upload_to='history/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pengaduan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_organisasi', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('nomor_sk', models.CharField(blank=True, max_length=100)),
                ('tanggal_sk', models.DateField(blank=True, null=True)),
                ('tanggal_berdiri', models.DateField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to='organisasi/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('status_verifikasi', models.BooleanField(default=False)),
                ('desa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.desa')),
                ('jenis_organisasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.jenisorganisasi')),
                ('ketua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('pesan', models.TextField()),
                ('status_baca', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MateriBerita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=20)),
                ('judul', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('deskripsi', models.TextField()),
                ('cover_image', models.ImageField(upload_to='materi/')),
                ('is_public', models.BooleanField(default=False)),
                ('status_publish', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LampiranPengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pengaduan/')),
                ('jenis_file', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pengaduan')),
            ],
        ),
        migrations.CreateModel(
            name='Dinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.TextField(blank=True)),
                ('telepon', models.CharField(blank=True, max_length=30)),
                ('kepala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinas_dipimpin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='desa',
            name='kecamatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kecamatan'),
        ),
        migrations.AddField(
            model_name='bidang',
            name='dinas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dinas'),
        ),
        migrations.AddField(
            model_name='bidang',
            name='kepala_bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bidang_dipimpin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AnggotaOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nik', models.CharField(max_length=16)),
                ('jabatan', models.CharField(max_length=100)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('organisasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisasi')),
            ],
        ),
        migrations.CreateModel(
            name='AktivitasPegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='aktivitas/')),
                ('tanggal_aktivitas', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
