# Generated by Django 4.2.30 on 2026-06-25 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisUsaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmJUsaha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmKelo', models.CharField(max_length=150)),
                ('kelas', models.CharField(max_length=50)),
                ('ketua', models.CharField(max_length=100)),
                ('koordinat', models.CharField(max_length=100)),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.desa')),
            ],
        ),
        migrations.CreateModel(
            name='ListUsaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komoditi', models.CharField(max_length=100)),
                ('wadah', models.CharField(max_length=100)),
                ('teknologi', models.CharField(max_length=100)),
                ('lahan', models.CharField(max_length=100)),
                ('tglMulai', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('jenisUsaha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jenisusaha')),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kelompok')),
            ],
        ),
        migrations.CreateModel(
            name='Pendapatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreate', models.DateField()),
                ('pendapatan', models.FloatField()),
                ('pengeluaran', models.FloatField()),
                ('laba', models.FloatField()),
                ('kas', models.FloatField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('aprovalPengawal', models.BooleanField(default=False)),
                ('aprovalDesa', models.BooleanField(default=False)),
                ('aprovalKec', models.BooleanField(default=False)),
                ('ketPengawal', models.TextField(blank=True, null=True)),
                ('ketDesa', models.TextField(blank=True, null=True)),
                ('ketKec', models.TextField(blank=True, null=True)),
                ('tglPengawal', models.DateField(blank=True, null=True)),
                ('tglDesa', models.DateField(blank=True, null=True)),
                ('tglKec', models.DateField(blank=True, null=True)),
                ('usaha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listusaha')),
            ],
        ),
    ]
