# Generated by Django 4.2.30 on 2026-06-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jenisusaha_kelompok_listusaha_pendapatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLegalitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmILega', models.CharField(max_length=100)),
                ('jenisValue', models.CharField(max_length=20)),
                ('idJLega', models.CharField(max_length=100)),
            ],
        ),
    ]
