# Generated by Django 4.2.30 on 2026-06-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itemlegalitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalitasKelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('aprovalPengawal', models.BooleanField(default=False)),
                ('aprovalDesa', models.BooleanField(default=False)),
                ('aprovalKec', models.BooleanField(default=False)),
                ('ketPengawal', models.TextField(blank=True, null=True)),
                ('ketDesa', models.TextField(blank=True, null=True)),
                ('ketKec', models.TextField(blank=True, null=True)),
                ('tglPengawal', models.DateField(blank=True, null=True)),
                ('tglDesa', models.DateField(blank=True, null=True)),
                ('tglKec', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itemLegalitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemlegalitas')),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kelompok')),
            ],
            options={
                'unique_together': {('kelompok', 'itemLegalitas')},
            },
        ),
    ]
