# Generated by Django 4.2.30 on 2026-06-27 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_legalitaskelompok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listusaha',
            name='tglMulai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AsetKelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaAset', models.CharField(max_length=150)),
                ('kategori', models.CharField(blank=True, max_length=100, null=True)),
                ('jumlah', models.IntegerField(default=1)),
                ('kondisi', models.CharField(choices=[('baik', 'Baik'), ('rusak', 'Rusak'), ('perlu_perbaikan', 'Perlu Perbaikan')], default='baik', max_length=20)),
                ('nilai', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kelompok')),
            ],
        ),
        migrations.CreateModel(
            name='AnggotaKelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('nik', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('noHp', models.CharField(blank=True, max_length=20, null=True)),
                ('jabatan', models.CharField(choices=[('ketua', 'Ketua'), ('sekretaris', 'Sekretaris'), ('bendahara', 'Bendahara'), ('anggota', 'Anggota')], default='anggota', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kelompok')),
            ],
        ),
    ]
