# Generated by Django 4.2.30 on 2026-06-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_listusaha_tglmulai_asetkelompok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendapatan',
            name='jenis',
            field=models.CharField(choices=[('UMUM', 'Umum'), ('PADES', 'PADes'), ('PAJAK', 'Pajak')], default='UMUM', max_length=10),
        ),
    ]
