# Generated by Django 4.2.30 on 2026-07-01 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pendapatan_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilayahpengawas',
            name='kelompok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kelompok'),
        ),
    ]
