# Generated by Django 4.2.30 on 2026-07-05 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_wilayahpengawas_kelompok'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelompok',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kelompok',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kelompok',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='kelompok',
            name='jenisKelompok',
            field=models.CharField(choices=[('POKTAN', 'POKTAN'), ('GAPOKTAN', 'GAPOKTAN'), ('BUMDES', 'BUMDES'), ('PKK', 'PKK'), ('KARANG_TARUNA', 'KARANG TARUNA'), ('KDMP', 'KDMP')], default='POKTAN', max_length=30),
        ),
        migrations.AddField(
            model_name='kelompok',
            name='jumlahAnggota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kelompok',
            name='jumlahPengelola',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kelompok',
            name='komoditasUtama',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kelompok',
            name='luasLahan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='kelompok',
            name='namaAwal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kelompok',
            name='noHp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kelompok',
            name='statusOperasional',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kelompok',
            name='tahunBerdiri',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kelompok',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='legalitaskelompok',
            name='fileDokumen',
            field=models.FileField(blank=True, null=True, upload_to='legalitas/'),
        ),
        migrations.AddField(
            model_name='listusaha',
            name='penanggungJawab',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='anggotakelompok',
            name='jabatan',
            field=models.CharField(choices=[('direktur', 'Direktur'), ('ketua', 'Ketua'), ('sekretaris', 'Sekretaris'), ('bendahara', 'Bendahara'), ('anggota', 'Anggota')], default='anggota', max_length=50),
        ),
        migrations.AlterField(
            model_name='asetkelompok',
            name='nilai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='kelompok',
            name='kelas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kelompok',
            name='ketua',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='kelompok',
            name='koordinat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='legalitaskelompok',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listusaha',
            name='komoditi',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='listusaha',
            name='lahan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='listusaha',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listusaha',
            name='teknologi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='listusaha',
            name='wadah',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='wilayahpengawas',
            name='kelompok',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='desa', chained_model_field='desa', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kelompok'),
        ),
    ]
