# Generated by Django 4.2.30 on 2026-07-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_kelompok_alamat_kelompok_created_at_kelompok_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelompok',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
