# Generated by Django 4.2.30 on 2026-07-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_kelompok_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelompok',
            name='jumlahPengelola',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
