# Generated by Django 4.2.30 on 2026-07-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_kelompok_jumlahpengelola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelompok',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='kelompok',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
