# Generated by Django 4.2.30 on 2026-07-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_kelompok_created_at_alter_kelompok_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listusaha',
            name='komoditi',
        ),
        migrations.RemoveField(
            model_name='listusaha',
            name='lahan',
        ),
        migrations.RemoveField(
            model_name='listusaha',
            name='penanggungJawab',
        ),
        migrations.RemoveField(
            model_name='listusaha',
            name='status',
        ),
        migrations.RemoveField(
            model_name='listusaha',
            name='teknologi',
        ),
        migrations.RemoveField(
            model_name='listusaha',
            name='tglMulai',
        ),
        migrations.RemoveField(
            model_name='listusaha',
            name='wadah',
        ),
    ]
