# Generated by Django 4.2.30 on 2026-08-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktivitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitaspegawai',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='aktivitaspegawai',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
    ]
