"""
Django settings for kawal_LPMD project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import mimetypes
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from django.templatetags.static import static
from pathlib import Path


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j9mf#o%@q2l8s)r%!luw5dxlhsf%^kfc(&s$u2tr#20yd$*m95'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True 
# Application definition

INSTALLED_APPS = [
    # 'jazzmin',
    'unfold', 
    # 'admin_interface',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core.app_config.CoreConfig',
    'core.apps.accounts.apps.AccountsConfig',
    'core.apps.master.apps.MasterConfig',
    'core.apps.aktivitas.apps.AktivitasConfig',
    'core.apps.informasi.apps.InformasiConfig',
    'core.apps.organisasi.apps.OrganisasiConfig',
    'core.apps.pengaduan.apps.PengaduanConfig',

    'django_browser_reload',
    'rest_framework',
    "smart_selects",  
    'drf_spectacular',
    'rest_framework_simplejwt.token_blacklist',
]
UNFOLD = {
    "SITE_TITLE": "GARDA KSB",
    "SITE_HEADER": "GARDA KSB",
    "SITE_SYMBOL": "shield",
    "STYLES": [
        lambda request: static("css/admin-fix.css"),
    ],
    "SCRIPTS": [
        lambda request: static("js/admin-sidebar.js"),
    ],
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django_browser_reload.middleware.BrowserReloadMiddleware',
    
]

ROOT_URLCONF = 'PYmodule.urls'

BASE_DIR = Path(__file__).resolve().parent.parent
AUTH_USER_MODEL = "accounts.User" 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR /'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.menu_legalitas',
            ],
        },
    },
]

WSGI_APPLICATION = 'PYmodule.wsgi.application'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

mimetypes.add_type(
    "application/javascript",
    ".mjs"
)

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/' 
STATICFILES_DIRS = [
    BASE_DIR / "static"
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# LOGIN_REDIRECT_URL = 'dashboard'
# LOGOUT_REDIRECT_URL = '/login/'


LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'garda.kabsumbawabarat.com',
    'www.garda.kabsumbawabarat.com',
]


FIREBASE_SERVICE_ACCOUNT = os.path.join(
    BASE_DIR,
    "core",
    "services",
    "garda-a8eb9-firebase-adminsdk-fbsvc-0937560186.json"
)
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'API Sistem Mobile',
    'DESCRIPTION': 'REST API untuk aplikasi mobile',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}