# Generated by Django 5.2.16 on 2026-07-31 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKasus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_tiket', models.CharField(max_length=50, unique=True)),
                ('nama_pelapor', models.CharField(blank=True, max_length=255)),
                ('hp_pelapor', models.CharField(blank=True, max_length=20)),
                ('email_pelapor', models.EmailField(blank=True, max_length=254)),
                ('alamat_pelapor', models.TextField(blank=True)),
                ('lokasi_kejadian', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('waktu_kejadian', models.DateTimeField()),
                ('uraian', models.TextField()),
                ('pihak_terlibat', models.TextField(blank=True)),
                ('dampak', models.TextField(blank=True)),
                ('prioritas', models.CharField(default='SEDANG', max_length=20)),
                ('anonim', models.BooleanField(default=False)),
                ('source', models.CharField(default='WEB', max_length=20)),
                ('status', models.CharField(choices=[('BARU', 'BARU'), ('VERIFIKASI', 'VERIFIKASI'), ('DISPOSISI', 'DISPOSISI'), ('PROSES', 'PROSES'), ('MONITORING', 'MONITORING'), ('SELESAI', 'SELESAI'), ('DITUTUP', 'DITUTUP'), ('DITOLAK', 'DITOLAK')], default='BARU', max_length=25)),
                ('verifikasi_admin', models.BooleanField(default=False)),
                ('kesimpulan', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.desa')),
                ('jenis_kasus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pengaduan.jeniskasus')),
                ('pelapor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LampiranPengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pengaduan/')),
                ('jenis_file', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengaduan.pengaduan')),
            ],
        ),
        migrations.CreateModel(
            name='PengaduanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('status_lama', models.CharField(max_length=25)),
                ('status_baru', models.CharField(max_length=25)),
                ('dokumentasi', models.FileField(blank=True, upload_to='history/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengaduan.pengaduan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifikasiPengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peran', models.CharField(choices=[('PJ', 'Penanggung Jawab'), ('TIM', 'Tim')], max_length=10)),
                ('status_verifikasi', models.BooleanField(default=False)),
                ('catatan', models.TextField(blank=True)),
                ('tanggal_verifikasi', models.DateTimeField(blank=True, null=True)),
                ('pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengaduan.pengaduan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
