# Generated by Django 5.2.16 on 2026-07-31 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengaduan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pengaduan', 'verbose_name_plural': 'Pengaduan'},
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='hp_pelapor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='nama_pelapor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='pelapor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengaduan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='prioritas',
            field=models.CharField(choices=[('RENDAH', 'Rendah'), ('SEDANG', 'Sedang'), ('TINGGI', 'Tinggi'), ('DARURAT', 'Darurat')], default='SEDANG', max_length=20),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='source',
            field=models.CharField(choices=[('WEB', 'Web'), ('ANDROID', 'Android'), ('IOS', 'iOS'), ('ADMIN', 'Admin')], default='WEB', max_length=20),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(choices=[('BARU', 'Baru'), ('VERIFIKASI', 'Verifikasi'), ('DISPOSISI', 'Disposisi'), ('PROSES', 'Proses'), ('MONITORING', 'Monitoring'), ('SELESAI', 'Selesai'), ('DITUTUP', 'Ditutup'), ('DITOLAK', 'Ditolak')], default='BARU', max_length=25),
        ),
    ]
