# Generated by Django 5.2.16 on 2026-08-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0002_alter_pengaduan_options_alter_pengaduan_hp_pelapor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeniskasus',
            name='warna',
            field=models.CharField(default='#facc15', help_text='Format HEX, contoh #ef4444', max_length=7),
        ),
    ]
