# Generated by Django 5.2.16 on 2026-08-02 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('pengaduan', '0003_jeniskasus_warna'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='bidang_disposisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.bidang'),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='disposisi_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='disposisi_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengaduan_disposisi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='petugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengaduan_penanganan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='tindak_lanjut',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='verifikator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengaduan_verifikasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pengaduanhistory',
            name='bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.bidang'),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(choices=[('BARU', 'Baru'), ('VERIFIKASI', 'Verifikasi'), ('PIMPINAN', 'Menunggu Pimpinan'), ('PROSES', 'Proses'), ('MONITORING', 'Monitoring'), ('SELESAI', 'Selesai'), ('DITUTUP', 'Ditutup'), ('DITOLAK', 'Ditolak')], default='BARU', max_length=25),
        ),
        migrations.AlterField(
            model_name='pengaduanhistory',
            name='pengaduan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='pengaduan.pengaduan'),
        ),
    ]
