# Generated by Django 5.2.16 on 2026-08-02 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0004_pengaduan_bidang_disposisi_pengaduan_disposisi_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='judul',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='jenis_kasus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pengaduan.jeniskasus'),
        ),
    ]
