# Generated by Django 5.2.16 on 2026-08-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0005_pengaduan_judul_alter_pengaduan_jenis_kasus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='lampiran',
            field=models.FileField(blank=True, null=True, upload_to='pengaduan/'),
        ),
    ]
