# Generated by Django 5.2.16 on 2026-08-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0007_alter_pengaduan_latitude_alter_pengaduan_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaduanhistory',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pengaduanhistory',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
