# Generated by Django 4.2.30 on 2026-08-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0008_alter_pengaduanhistory_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaduan',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verifikasipengaduan',
            name='peran',
            field=models.CharField(choices=[('PJ', 'Penanggung Jawab'), ('TIM', 'Tim / Anggota')], max_length=10),
        ),
    ]
